["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["profile.devnet.protostar.deploy"]
gateway-url="http://127.0.0.1:5050/"

["protostar.build"]
cairo-path = ['./lib/cairo_contracts/src']

["protostar.shared_command_configs"]
cairo-path = ["./lib/cairo_contracts/src"]

["protostar.contracts"]
# main = [
#     "src/main.cairo",
# ]
proxy = [
    "src/Proxy.cairo",
]
A = [
    "src/A.cairo"
]
B = [
    "src/B.cairo"
]
A_new = [
    "src/A_new.cairo"
]

