["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
# main = [
#     "src/main.cairo",
# ]
proxy = [
    "src/Proxy.cairo",
]
A = [
    "src/A.cairo"
]
B = [
    "src/B.cairo"
]
A_new = [
    "src/A_new.cairo"
]